### ISSUE TITLE
Browsing for a file to open

### ISSUE THREAD

**Issue by metalman4411** [flathub/com.google.EarthPro#1]
When I want to open a KMZ file in Google Earth flatpak version, or use any other command that browses for a file on disk, in "Open" dialog box, only Downloads folder is visible under my local system Home folder. It does not see other folders.
Thank you for your attention.

![Screenshot_2023-07-15_09-55-28](https://github.com/flathub/com.google.EarthPro/assets/139615987/cc22b920-0678-497d-8e56-5609c6a1fc26)

**Comment by hfiguiere** [comment]
for security reasons the sandbox as restricted access, only Downloads is available.

**Comment by ghazyami** [comment]
@metalman4411 fell free to grant access to additional directories if you want.
[Flatseal](https://flathub.org/en-GB/apps/com.github.tchx84.Flatseal) can help with managing your flatpaks

**Comment by metalman4411** [comment]
Thank you for your reply.
I turned on in Flatseal "Filesystem->All user files" and got access to my Home folder. Alas, I lost all my saved My Places. I have to admit I was quite annoyed thinking I lost months of work, but anyway, I decided to turn it off again, and to my surprise I got My Places back. I was wondering where did Earth pulled them from and I searched for folder where myplaces.kml is stored. Apparently, there are two locations: /home/<username>/.googleearth/ and /home/<username>/.var/app/com.google.EarthPro/.googleearth/; former is used when "All user files" is turned on, and latter is used when "All user files" is turned off? Is this by design?

**Comment by ghazyami** [comment]
@metalman4411 this is expected for how this Flatpak is configured.
Usually, Google Earth keeps information in `.googleearth` directory under user's home.
But the flatpak is configured to have a mount for this directory, so it will be under `.var/app/com.google.EarthPro/.googleearth` instead (out of separating idea, like the Flatpak sandbox).

In your case, you can grant re-enable `All user files` and copy contents of `/home/username/.var/app/com.google.EarthPro/.googleearth` into `/home/username/.googleearth`. Or grant access to specific directory that you want to import / open files from.

**Comment by metalman4411** [comment]
@ghazyami It is interesting however that when I give it "All user files" permission, it starts to use `/home/username/.googleearth/` folder, just like non-flatpak app would. I thought flatpak apps always used `/home/username/.var/app/` as starting folder.
Also, for example, flatpak version of Firefox browser does not have any of permissions listed under "Filesystem" in Flatseal, yet when I click "Open File" command in Firefox, I can browse all folders from my system, including entire `/` folder.

**Comment by ghazyami** [comment]
@metalman4411 I am not using Firefox version, but there is Flatpak Portal feature, that can grant temporary access on the fly while browsing, and it will show up as `/run/user/<XXXX>/doc/<YYYYYYY>/<directory-name>` instead of the actual path, Firefox could be using that
