### ISSUE TITLE
Google Earth fails to open

### ISSUE THREAD

**Issue by grb43** [flathub/com.google.EarthPro#12]
I'm running (openSUSE) Aeon (Gnome desktop). The system and flathub packages are fully up to date.

org.freedesktop.Platform and org.freedesktop.Sdk are both at version/branch 23.08.

Google Earth Pro flatpak fails to open from both GUI and CLI. Other flatpaks work fine.

From the command line:
:~> flatpak run com.google.EarthPro
/app/extra/google/earth/pro/googleearth-bin: error while loading shared libraries: libcrypto.so.1.0.0: cannot enable executable stack as shared object requires: Permission denied

I've tried opening up most Google Earth flatpak permissions with flatseal but that didn't help.

Any assistance would be appreciated.

**Comment by ghazyami** [comment]
No idea what could be the issue, can you check SELinux?

**Comment by grb43** [comment]
Thanks for replying.

Yes, disabling SELinux fixes the problem.

I'll try and figure out how to fix this permanently.

Thanks again

**Comment by grb43** [comment]
The following procedure seemed to fix the SELinux problem for me, remember I'm using (openSuse) Aeon:

Run the following command: 
`sudo audit2why -b`

The output confirms there is an SELinux problem and suggests the following command be run:
`sudo setsebool -P selinuxuser_execstack 1`

This command stopped the error message but Earth now claimed an instance was already running and refused to start.

Once I found and removed the stale lock-file directory at ~/.var/app/com.google.EarthPro/.googleearth/instance-running-lock everything worked as expected.

The above procedure is persistant across reboots; hopefully it hasn't opened the machine to attacks from other bibaries.

**Comment by ghazyami** [comment]
Thanks for checking and the detailed info
